---
- name: Create Zookeeper containers
  docker_container:
    name: "{{ zookeeper_name }}{{ item }}"
    image: "{{ zookeeper_image }}"
    state: present
    restart_policy: "{{ zookeeper_restart_policy }}"
    env:
      ZOOKEEPER_ID: "{{ item | string }}"
      ZOOKEEPER_NODE_COUNT: "{{ kafka_replication_factor | string }}"
    ports:
      - "{{ zookeeper_port + item - 1 }}:{{ zookeeper_port + item - 1 }}"
    networks:
      - name: "{{ kafka_network }}"
      - name: "{{ logging_network }}"
  loop: "{{ range(1, kafka_replication_factor + 1) | list }}"