---
- name: Create Node-Exporter container
  docker_container:
    name: "{{ node_exporter_name }}"
    image: "{{ node_exporter_image }}"
    state: present
    restart_policy: "{{ node_exporter_restart_policy }}"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    env:
      TZ: "{{ node_exporter_env_timezone }}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "{{ node_exporter_port }}:9100"
    networks:
      - name: "{{ monitoring_network }}"
      - name: "{{ logging_network }}"